# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [237]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [286]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [287]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [288]:
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [289]:
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [290]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [291]:
# Import `train_test_split` from `sklearn.model_selection`
from sklearn.model_selection import train_test_split

# Specify the data 
X=df.ix[:,0:4]

# Specify the target labels and flatten the array
y= df.ix[:,4]
#y= wines.type

# Split the data up in train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=21)

/Users/SaravanaTK/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """
/Users/SaravanaTK/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


In [292]:
y_test

92     1.0
44     0.0
7      0.0
21     0.0
95     1.0
75     1.0
20     0.0
121    2.0
26     0.0
19     0.0
81     1.0
88     1.0
143    2.0
117    2.0
23     0.0
77     1.0
138    2.0
73     1.0
14     0.0
142    2.0
123    2.0
62     1.0
83     1.0
74     1.0
42     0.0
60     1.0
40     0.0
45     0.0
87     1.0
124    2.0
41     0.0
131    2.0
70     1.0
46     0.0
126    2.0
54     1.0
85     1.0
114    2.0
Name: target, dtype: float64

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [293]:
from tensorflow import keras

y_train = keras.utils.to_categorical(y_train, 3)
y_test = keras.utils.to_categorical(y_test, 3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [294]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
# Initialize the constructor

model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [295]:
# Define model architecture

model.add(Dense(3, activation='softmax', input_shape=(4,)))
#model.add(Dense(3,activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [296]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [297]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [298]:
history = model.fit(X_train, y_train,epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 1s 5ms/sample - loss: 1.1849 - accuracy: 0.4196
Epoch 2/100
112/112 [==============================] - 0s 4ms/sample - loss: 0.7026 - accuracy: 0.6964
Epoch 3/100
112/112 [==============================] - 0s 3ms/sample - loss: 0.6008 - accuracy: 0.7054
Epoch 4/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.5066 - accuracy: 0.7589
Epoch 5/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.4989 - accuracy: 0.7500
Epoch 6/100
112/112 [==============================] - 0s 3ms/sample - loss: 0.4684 - accuracy: 0.7857
Epoch 7/100
112/112 [==============================] - 0s 3ms/sample - loss: 0.4432 - accuracy: 0.8125
Epoch 8/100
112/112 [==============================] - 1s 5ms/sample - loss: 0.4168 - accuracy: 0.8036
Epoch 9/100
112/112 [==============================] - 0s 4ms/sample - loss: 0.4060 - accuracy: 0.8393
Epoch 10/100
112/112 [==============================

112/112 [==============================] - 0s 2ms/sample - loss: 0.1230 - accuracy: 0.9821
Epoch 78/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1171 - accuracy: 0.9911
Epoch 79/100
112/112 [==============================] - 0s 4ms/sample - loss: 0.1214 - accuracy: 0.9821
Epoch 80/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1212 - accuracy: 0.9732
Epoch 81/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1251 - accuracy: 0.9732
Epoch 82/100
112/112 [==============================] - 0s 3ms/sample - loss: 0.1219 - accuracy: 0.9554
Epoch 83/100
112/112 [==============================] - 0s 3ms/sample - loss: 0.1194 - accuracy: 0.9732
Epoch 84/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1223 - accuracy: 0.9732
Epoch 85/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1212 - accuracy: 0.9911
Epoch 86/100
112/112 [==============================] - 0s 2ms/sample - loss:

## Question 10

### Make predictions
- Predict labels on one row

In [299]:
X_test
y_pred = np.round(model.predict(X_test))
y_pred[0]

array([0., 1., 0.], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [300]:
y_test[0]

array([0., 1., 0.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [301]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [302]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [304]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [305]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [306]:
df_prices = pd.read_csv('prices.csv')

In [307]:
df_prices

date symbol        open       close         low  \
0       2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998   
1       2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002   
2       2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000   
3       2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000   
4       2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996   
...                     ...    ...         ...         ...         ...   
851259           2016-12-30    ZBH  103.309998  103.199997  102.849998   
851260           2016-12-30   ZION   43.070000   43.040001   42.689999   
851261           2016-12-30    ZTS   53.639999   53.529999   53.270000   
851262  2016-12-30 00:00:00    AIV   44.730000   45.450001   44.410000   
851263  2016-12-30 00:00:00    FTV   54.200001   53.630001   53.389999   

              high     volume  
0       126.250000  2163600.0  
1       125.540001  2386400.0  
2       119.739998  2489500.0  
3       117.440002  2006300.0  
4       117.330002  1408600.0  
...            ...        ...  
851259  103.930000   973800.0  
851260   43.310001  1938100.0  
851261   53.740002  1701200.0  
851262   45.590000  1380900.0  
851263   54.480000   705100.0  

[851264 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [308]:
df_prices.drop(['date','symbol'], axis=1, inplace = True)
df_prices

open       close         low        high     volume
0       123.430000  125.839996  122.309998  126.250000  2163600.0
1       125.239998  119.980003  119.940002  125.540001  2386400.0
2       116.379997  114.949997  114.930000  119.739998  2489500.0
3       115.480003  116.620003  113.500000  117.440002  2006300.0
4       117.010002  114.970001  114.089996  117.330002  1408600.0
...            ...         ...         ...         ...        ...
851259  103.309998  103.199997  102.849998  103.930000   973800.0
851260   43.070000   43.040001   42.689999   43.310001  1938100.0
851261   53.639999   53.529999   53.270000   53.740002  1701200.0
851262   44.730000   45.450001   44.410000   45.590000  1380900.0
851263   54.200001   53.630001   53.389999   54.480000   705100.0

[851264 rows x 5 columns]

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [309]:
df_prices = df_prices.head(1000)
df_prices

open       close         low        high      volume
0    123.430000  125.839996  122.309998  126.250000   2163600.0
1    125.239998  119.980003  119.940002  125.540001   2386400.0
2    116.379997  114.949997  114.930000  119.739998   2489500.0
3    115.480003  116.620003  113.500000  117.440002   2006300.0
4    117.010002  114.970001  114.089996  117.330002   1408600.0
..          ...         ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999   2133200.0
996   27.160000   26.990000   26.680000   27.299999   1982400.0
997   28.320000   28.770000   28.010000   28.809999  37152800.0
998   44.000000   44.799999   43.750000   44.810001   6568600.0
999   36.080002   37.139999   36.009998   37.230000   5604300.0

[1000 rows x 5 columns]

In [310]:
df_prices.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [311]:
X=df_prices.ix[:,0:4]

# Specify the target labels and flatten the array
y= df_prices.ix[:,4]

/Users/SaravanaTK/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/Users/SaravanaTK/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


In [324]:
X

<tf.Tensor: id=2154746, shape=(1000, 4), dtype=float32, numpy=
array([[0.4958289 , 0.50551003, 0.49132976, 0.5071571 ],
       [0.51032925, 0.48889577, 0.48873278, 0.51155174],
       [0.49941418, 0.49327773, 0.4931919 , 0.51383275],
       ...,
       [0.49720097, 0.50510144, 0.49175844, 0.50580364],
       [0.4961377 , 0.50515836, 0.49331874, 0.50527114],
       [0.49263427, 0.50710744, 0.49167845, 0.50833625]], dtype=float32)>

In [313]:
y = y/1000000 

In [314]:
y

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [315]:
X = X.to_numpy(dtype = 'float32' )
y = y.to_numpy(dtype = 'float32' )

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [316]:
X = tf.math.l2_normalize(X, axis=1)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [333]:
W = tf.zeros([1,4])

b = tf.zeros(1)

In [349]:
W = tf.transpose(W)

In [350]:
W

<tf.Tensor: id=2157740, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [364]:
import numpy as np
#@tf.function
def get_prediction(X, W, b):
    prediction = np.dot(X,W) + b
    return prediction

In [365]:
print(get_prediction(X, W, b))

NotImplementedError: in converted code:

    <ipython-input-364-45873effdc6b>:4 get_prediction  *
        prediction = np.dot(X,W) + b
    <__array_function__ internals>:6 dot
        
    /Users/SaravanaTK/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:736 __array__
        " array.".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (W:0) to a numpy array.


### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [363]:

#training info
train_steps = 100
learning_rate = 0.01

for i in range(train_steps):
  
  #watch the gradient flow 
  with tf.GradientTape() as tape:
    
    #forward pass 
    yhat = get_prediction(X, W, b)
    
    #calcuate the loss (difference squared error)
    #a_list = tf.unstack(yhat)
    #for j in range(100):
    #    a_list[j] = yhat[j,0:1] + yhat[j,1:2] + yhat[j,2:3] + yhat[j,3:4]
    #yhat = tf.stack(a_list)
    
    #yhat = yhat[0, 3:4]
    #print(yhat)
    error = yhat - y
    loss = tf.reduce_mean(tf.square(error))
    print(error)
    print(loss)
  
    #evalute the gradient with the respect to the paramters
    gradients = tape.gradient(loss, [W, b])
    print(gradients)
    #print(db)
    #update the paramters using Gradient Descent  
    #W.assign_sub(dW * learning_rate)
    #b.assign_sub(db * learning_rate)

  #print the loss every 20 iterations 
  if i % 20 == 0:
    print("Loss at step {:03d}: {:.3f}".format(i, loss))
      
print(f'W : {W.numpy()} , b  = {b.numpy()} ')

tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 ...
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]], shape=(1000, 1000), dtype=float32)
tf.Tensor(237.28665, shape=(), dtype=float32)
[None, None]
Loss at step 000: 237.287
tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 ...
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]], shape=(1000, 1000), dtype=float32)
tf.Tensor(237.28665, shape=(), dtype=float32)
[None, None]
tf.Tensor(
[[ -2.1

tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 ...
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]], shape=(1000, 1000), dtype=float32)
tf.Tensor(237.28665, shape=(), dtype=float32)
[None, None]
tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 ...
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]], shape=(1000, 1000), dtype=float32)
tf.Tensor(237.28665, shape=(), dtype=float32)
[None, None]
tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... 

tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 ...
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]], shape=(1000, 1000), dtype=float32)
tf.Tensor(237.28665, shape=(), dtype=float32)
[None, None]
tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 ...
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]], shape=(1000, 1000), dtype=float32)
tf.Tensor(237.28665, shape=(), dtype=float32)
[None, None]
tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... 

tf.Tensor(
[[ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 ...
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]
 [ -2.1636  -2.3864  -2.4895 ... -37.1528  -6.5686  -5.6043]], shape=(1000, 1000), dtype=float32)
tf.Tensor(237.28665, shape=(), dtype=float32)
[None, None]
W : [[0.]
 [0.]
 [0.]
 [0.]] , b  = [0.] 


### Observe values of Weight
- Print the updated values

In [ ]:
W.numpy()

### Observe values of Bias
- Print the updated values

In [ ]:
b.numpy()

In [ ]:
X[0].numpy()

In [ ]:
(X[0,0]*W) + (X[0,1]*W) + (X[0,2]*W) + (X[0,3]*W) + b

In [ ]:
y[0]